config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #devise_for :models
  resources :tasks
  resources :projects

   get 'tasks/new/:project_id', to: 'tasks#new'
   root to: "projects#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    if current_user.is_admin
      @projects = Project.all
    else
      @projects = current_user.projects
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    # Monte Carlo Simulation
    if params[:epochs] == nil or params[:epochs].to_i == 0
      @epochs = 1000
    else
      @epochs = params[:epochs].to_i
      if @epochs>5000
        @epochs=5000
      end
    end
    if params[:dist] == nil or params[:dist] == ""
      dist='normal'
    else
      dist=params[:dist]
    end

    simulate(@project,@epochs,dist)
  end

  # GET /projects/new
  def new
    @project = Project.new()
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  protected

  def simulate(project,epochs,dist)

    @dur_simulation = []
    @dur_sim_freq = {}
    @dur_sim_freq_cumul = {}
    @cost_simulation = []
    @cost_sim_freq = {}
    @cost_sim_freq_cumul = {}
    dur_simulations_params=[]
    cost_simulations_params=[]
    for i in 1..epochs
      current_dur_simulation_params={}
      current_dur_simulation_params['tasks']=[]
      current_cost_simulation_params={}
      current_cost_simulation_params['tasks']=[]
      current_dur_simulation = 0
      min_dur=0
      max_dur=0
      current_cost_simulation = 0
      min_cost=0
      max_cost=0
      take_number=0
      project.tasks.each do |task|
        task.duration_lb = 0 unless task.duration_lb != nil
        task.duration_ub = 0 unless task.duration_ub != nil
        task.cost_ub = 0 unless task.cost_ub != nil
        task.cost_lb = 0 unless task.cost_lb != nil

        take_number+=1
        if dist == 'uniform'
          current_dur_simulation += rand(task.duration_lb..task.duration_ub)
          current_cost_simulation += rand(task.cost_lb..task.cost_ub)
        elsif dist == 'normal'
          dur_mean = (task.duration_lb + task.duration_ub) / 2
          cost_mean = (task.cost_lb + task.cost_ub) / 2
          dur_stdrd_dev = (task.duration_ub - task.duration_lb) / 3.29
          cost_stdrd_dev = (task.cost_ub - task.cost_lb) / 3.29
          current_dur_simulation_params['tasks'] << {'mean':dur_mean,'stdr_dev':dur_stdrd_dev,'prob':rand}
          current_cost_simulation_params['tasks'] << {'mean':cost_mean,'stdr_dev':cost_stdrd_dev,'prob':rand}
        end

        min_dur += task.duration_lb
        max_dur += task.duration_ub
        min_cost += task.cost_lb.to_i
        max_cost += task.cost_ub.to_i

      end
      if dist == 'normal'
        dur_simulations_params.append(current_dur_simulation_params)
        cost_simulations_params.append(current_cost_simulation_params)
      elsif dist == 'uniform'
        @dur_simulation << current_dur_simulation.to_i
        @cost_simulation << current_cost_simulation.to_i
      end
    end

    if dist=='normal'
      #  write the json params to a json file
      dur_param_file_name = "tmp/simulation_params/"+Time.now.to_i.to_s+"_dur_"+current_user.id.to_s+'.json'
      File.open(dur_param_file_name, "w") { |f| f.write dur_simulations_params.to_json.to_s }

    #cmd = "python3.8 norm_inv.py '"+dur_simulations_params.to_json.to_s+"'"
    cmd = "python3.8 norm_inv.py "+dur_param_file_name
    result = `#{cmd}`
    result_array=result.split(',')
    result_array.each do |value|
      @dur_simulation << value.to_i
    end

    cost_param_file_name = "tmp/simulation_params/"+Time.now.to_i.to_s+"_cost_"+current_user.id.to_s+'.json'
    File.open(cost_param_file_name, "w") { |f| f.write cost_simulations_params.to_json.to_s }
    cmd = "python3.8 norm_inv.py "+cost_param_file_name
    result = `#{cmd}`
    result_array=result.split(',')
    result_array.each do |value|
      @cost_simulation << value.to_i
    end

    end

    for i in (min_dur..max_dur).step(1)
      @dur_sim_freq[i]=@dur_simulation.count(i)*100/@dur_simulation.length.to_d
      #@cost_sim_freq[i]=@cost_simulation.count(i)
    end
    for i in (min_cost..max_cost).step(1)
      @cost_sim_freq[i]=@cost_simulation.count(i)*100/@cost_simulation.length.to_d
    end

    i = 0
    cumul=0
    @dur_sim_freq.each do |dur,freq|
      if (i != 0)
        cumul+= freq unless i == 0
        @dur_sim_freq_cumul[dur] = cumul
      else
        @dur_sim_freq_cumul[dur] = freq
      end
      i+=1
    end


    i = 0
    cumul=0
    @cost_sim_freq.each do |cost,freq|
      if (i != 0)
        cumul+= freq unless i == 0
        @cost_sim_freq_cumul[cost] = cumul
      else
        @cost_sim_freq_cumul[cost] = freq
      end
      i+=1
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description,:metric_one_label,:metric_two_label,:user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="form_container">
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :"Metric one label" %>
    <%= form.text_field :metric_one_label %>
  </div>

  <div class="field">
    <%= form.label :"Metric two label" %>
    <%= form.text_field :metric_two_label %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/projects/_navigation.html.erb
<div class="navigation">
<%= link_to 'New Project', new_project_path %>
| <%= link_to 'My Projects', projects_path %>
</div>

app/views/projects/edit.html.erb
<%= render 'navigation' %>


<h1>Editing Project</h1>



<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |

app/views/projects/index.html.erb
<%= render 'navigation' %>

<p id="notice"><%= notice %></p>


<h2>Projects</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/projects/new.html.erb
<%= render 'navigation' %>

<h2>Add a New Project</h2>



<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>


<%= render 'navigation' %>


<h2><%= @project.name %></h2>
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>




<h3>Project tasks</h3>

<div style="width:100%;text-align:right">
<%= link_to 'Add  a new  Task', new_task_path(:project_id=>@project.id) %>
</div>

<% if @project.tasks.count>0%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>

      <th><%= @project.metric_one_label+" LB" %></th>
      <th><%= @project.metric_one_label+" UB" %></th>
      <th><%= @project.metric_two_label+" LB" %></th>
      <th><%= @project.metric_two_label+" UB" %></th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <% duration_lb_total = 0 %>
  <% duration_ub_total = 0 %>
  <% cost_lb_total = 0 %>
  <% cost_ub_total = 0 %>
  <tbody>
    <% @project.tasks.each do |task| %>
    <% duration_lb_total+=task.duration_lb%>
    <% duration_ub_total+=task.duration_ub%>
    <% cost_lb_total+=task.cost_lb%>
    <% cost_ub_total+=task.cost_ub%>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.duration_lb %></td>
        <td><%= task.duration_ub %></td>
        <td><%= task.cost_lb %></td>
        <td><%= task.cost_ub %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
    <td>TOTAL</td>
    <td></td>
    <td><%= duration_lb_total %></td>
    <td><%= duration_ub_total %></td>
    <td><%= cost_lb_total %></td>
    <td><%= cost_ub_total %></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  </tbody>
</table>


<h3>Simulation parameters</h3>
<div class="form_container">
<form action="?" method="get">
  Epochs
  <input type="text" name="epochs" value="<%= @epochs %>">
   Distribution
  <select name="dist">

    <% if params[:dist] == "normal" %>
    <option value="normal" selected="selected">Normal</option>
    <% else %>
    <option value="normal">Normal</option>
    <% end %>
    <% if params[:dist] == "uniform" %>
    <option value="uniform" selected="selected">Uniform</option>
    <% else %>
    <option value="uniform">Uniform</option>
    <% end %>

  </select>
  <input type="submit" value="Run simulation">
</form>
</div>

<h3><%= @project.metric_one_label%> Simulation</h3>


<strong>Outcome frequencies histogram</strong>
<%= column_chart( @dur_sim_freq,width: "100%") %>
<br>
<strong>Outcome cumulatime curve</strong>
<%= line_chart( @dur_sim_freq_cumul, points: false,width: "100%") %>
<br>
<strong>Simulation comments</strong>
<% for cumul_percent in (70..90).step(10) %>
  <% @dur_sim_freq_cumul.each do |key,value| %>
  <% if value >= cumul_percent %>
  <p>There is an <%= value %>% probability that the outcome of <%=@project.metric_one_label%> will be <%= key %> or less </p>
  <% break %>
  <% end %>
  <% end  %>
<% end %>

<br><hr width="80%"><br>

<h4><%= @project.metric_two_label%> Simulation</h4>

<strong>Outcome frequencies histogram</strong>

<%= column_chart( @cost_sim_freq,width: "100%") %>
<br>
<strong>Outcome cumulatime curve</strong>
<%= line_chart( @cost_sim_freq_cumul, points: false,width: "100%") %>
<br>
<strong>Simulation comments</strong>
<% for cumul_percent in (70..90).step(10) %>
  <% @cost_sim_freq_cumul.each do |key,value| %>
  <% if value >= cumul_percent %>
  <p>There is an <%= value %>% probability that the outcome of <%=@project.metric_two_label%> will be  <%= key %> or less </p>
  <% break %>
  <% end %>
  <% end  %>
<% end  %>

<% else %>
<i>Add tasks to make a simulation</i>
<% end %>